[workspace]
authors = ["Emmanuelle Sarrazin <emmanuelle.sarrazin@cnes.fr>"]
channels = ["conda-forge"]
name = "big-data-processing-course-tutorials"
description = "Tutorials for big data processing course"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.14.*"
pip = ">=26.0.1,<27"
numba = ">=0.63.1,<0.64"
pandas = ">=3.0.1,<4"
numpy = ">=2.3.5,<3"
jupyterlab = ">=4.5.4,<5"
matplotlib = ">=3.10.8,<4"
geopandas = ">=1.1.2,<2"
geodatasets = ">=2026.1.0,<2027"
xarray = ">=2026.2.0,<2027"
h5netcdf = ">=1.8.1,<2"
netcdf4 = ">=1.7.4,<2"
scikit-learn = ">=1.8.0,<2"
joblib = ">=1.5.3,<2"
pyarrow = ">=23.0.1,<24"

[pypi-dependencies]
memory-profiler = ">=0.61.0, <0.62"


